<link rel="stylesheet" type="text/css" href="{{url('customer')}}/css/animate.css">
<link rel="stylesheet" type="text/css" href="{{url('customer')}}/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{{url('customer')}}/css/jquery.range.css">
<link rel="stylesheet" type="text/css" href="{{url('customer')}}/css/line-awesome.css">
<link rel="stylesheet" type="text/css" href="{{url('customer')}}/css/line-awesome-font-awesome.min.css">
<link href="{{url('customer')}}/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{{url('customer')}}/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="{{url('customer')}}/lib/slick/slick.css">
<link rel="stylesheet" type="text/css" href="{{url('customer')}}/lib/slick/slick-theme.css">
<link rel="stylesheet" type="text/css" href="{{url('customer')}}/css/style.css">
<link rel="stylesheet" type="text/css" href="{{url('customer')}}/css/responsive.css">
<link rel="stylesheet" type="text/css" href="{{url('css/customer.css')}}">
